Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Metrics/ClassLength:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: true
  EnforcedStyle: context_dependent

Style/LeadingCommentSpace:
  Enabled: true

Style/ExtraSpacing:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Style/DoubleNegation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading

# TODO: Reconfigure cops below or re-enable

# Offense count: 31
Lint/AmbiguousOperator:
  Enabled: false

# Offense count: 49
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# Offense count: 54
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Lint/BlockAlignment:
  Enabled: false

# Offense count: 3
# Configuration parameters: AlignWith, SupportedStyles.
Lint/DefEndAlignment:
  Enabled: false


# Offense count: 54
# Configuration parameters: AlignWith, SupportedStyles.
Lint/EndAlignment:
  Enabled: false

# Offense count: 1
Lint/EnsureReturn:
  Enabled: false

# Offense count: 10
Lint/Eval:
  Enabled: false

# Offense count: 1
Lint/HandleExceptions:
  Enabled: false

# Offense count: 2
Lint/Loop:
  Enabled: false

# Offense count: 130
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

# Offense count: 13
Lint/RescueException:
  Enabled: false

# Offense count: 54
Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Lint/SpaceBeforeFirstArg:
  Enabled: false

# Offense count: 28
# Cop supports --auto-correct.
Lint/StringConversionInInterpolation:
  Enabled: false

# Offense count: 1
Lint/UnderscorePrefixedVariableName:
  Enabled: false

# Offense count: 107
# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

# Offense count: 37
# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: false

# Offense count: 6
Lint/UselessAccessModifier:
  Enabled: false

# Offense count: 157
Lint/UselessAssignment:
  Enabled: false

# Offense count: 14
Lint/Void:
  Enabled: false

# Offense count: 396
Metrics/AbcSize:
  Max: 272

# Offense count: 4
Metrics/BlockNesting:
  Max: 4

# Offense count: 60
Metrics/CyclomaticComplexity:
  Max: 40

# Offense count: 535
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 264

# Offense count: 3
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

# Offense count: 48
Metrics/PerceivedComplexity:
  Max: 43

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AccessModifierIndentation:
  Enabled: false

# Offense count: 5
Style/AccessorMethodName:
  Enabled: false

# Offense count: 29
# Cop supports --auto-correct.
Style/AlignArray:
  Enabled: false

# Offense count: 133
# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
Style/AlignHash:
  Enabled: false

# Offense count: 143
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AlignParameters:
  Enabled: false

# Offense count: 129
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BarePercentLiterals:
  Enabled: false

# Offense count: 6
# Cop supports --auto-correct.
Style/BlockEndNewline:
  Enabled: false

# Offense count: 372
# Cop supports --auto-correct.
Style/Blocks:
  Enabled: false

# Offense count: 1
Style/CaseEquality:
  Enabled: false

# Offense count: 109
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: false

# Offense count: 201
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassCheck:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/ClassMethods:
  Enabled: false

# Offense count: 43
Style/ClassVars:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
Style/ColonMethodCall:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Style/CommentIndentation:
  Enabled: false

# Offense count: 2
Style/ConstantName:
  Enabled: false

# Offense count: 16
# Cop supports --auto-correct.
Style/DeprecatedHashMethods:
  Enabled: false

# Offense count: 1324
Style/Documentation:
  Enabled: false

# Offense count: 7
Style/EachWithObject:
  Enabled: false

# Offense count: 44
# Cop supports --auto-correct.
Style/ElseAlignment:
  Enabled: false

# Offense count: 8
Style/EmptyElse:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AllowAdjacentOneLineDefs.
Style/EmptyLineBetweenDefs:
  Enabled: false

# Offense count: 13
# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/EmptyLinesAroundAccessModifier:
  Enabled: false

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Enabled: false

# Offense count: 16
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundModuleBody:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Style/EmptyLiteral:
  Enabled: false

# Offense count: 56
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Offense count: 27
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Offense count: 139
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 87
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Offense count: 17
# Cop supports --auto-correct.
Style/IndentArray:
  Enabled: false

# Offense count: 21
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/IndentHash:
  Enabled: false

# Offense count: 48
# Cop supports --auto-correct.
Style/IndentationConsistency:
  Enabled: false

# Offense count: 77
# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Enabled: false

# Offense count: 127
Style/Lambda:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
Style/LineEndConcatenation:
  Enabled: false

# Offense count: 16
# Cop supports --auto-correct.
Style/MethodCallParentheses:
  Enabled: false

# Offense count: 21
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodDefParentheses:
  Enabled: false

# Offense count: 3
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodName:
  Enabled: false

# Offense count: 3
Style/ModuleFunction:
  Enabled: false

# Offense count: 6
Style/MultilineBlockChain:
  Enabled: false

# Offense count: 21
# Cop supports --auto-correct.
Style/MultilineBlockLayout:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/MultilineIfThen:
  Enabled: false

# Offense count: 279
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/NegatedIf:
  Enabled: false

# Offense count: 1
Style/NestedTernaryOperator:
  Enabled: false

# Offense count: 17
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
Style/Next:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/NilComparison:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/Not:
  Enabled: false

# Offense count: 6
# Cop supports --auto-correct.
Style/NumericLiterals:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: AllowSafeAssignment.
Style/ParenthesesAroundCondition:
  Enabled: false

# Offense count: 488
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false

# Offense count: 112
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/PercentQLiterals:
  Enabled: false

# Offense count: 30
# Cop supports --auto-correct.
Style/PerlBackrefs:
  Enabled: false

# Offense count: 7
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
Style/Proc:
  Enabled: false

# Offense count: 7
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/RaiseArgs:
  Enabled: false

# Offense count: 7
# Cop supports --auto-correct.
Style/RedundantBegin:
  Enabled: false

# Offense count: 9
Style/RedundantException:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: false

# Offense count: 513
# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

# Offense count: 23
# Configuration parameters: MaxSlashes.
Style/RegexpLiteral:
  Enabled: false

# Offense count: 3
Style/SelfAssignment:
  Enabled: false

# Offense count: 21
# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Enabled: false

# Offense count: 292
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: false

# Offense count: 4
# Configuration parameters: Methods.
Style/SingleLineBlockParams:
  Enabled: false

# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: AllowIfMethodIsEmpty.
Style/SingleLineMethods:
  Enabled: false

# Offense count: 224
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: false

# Offense count: 48
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# Offense count: 172
# Cop supports --auto-correct.
Style/SpaceAroundOperators:
  Enabled: false

# Offense count: 72
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceBeforeBlockBraces:
  Enabled: false

# Offense count: 17
# Cop supports --auto-correct.
Style/SpaceBeforeComma:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/SpaceBeforeComment:
  Enabled: false

# Offense count: 183
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 36
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: false

# Offense count: 2991
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: false

# Offense count: 12
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: false

# Offense count: 22
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/SymbolProc:
  Enabled: false

# Offense count: 13
# Cop supports --auto-correct.
Style/Tab:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: false

# Offense count: 4
Style/UnlessElse:
  Enabled: false

# Offense count: 119
# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Enabled: false

# Offense count: 3
# Configuration parameters: MaxLineLength.
Style/WhileUntilModifier:
  Enabled: false

# Offense count: 224
# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
Style/WordArray:
  MinSize: 12
